In [1]:
 import numpy as np
Numb_students=int(input("enter the  number  of students "))
Numb_subjets=int(input("enter the  number of subjets "))

enter the  number  of students 3
enter the  number of subjets 3


In [9]:
 a = np.zeros(shape=(3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
a[0] = [84, 95,89]
a[1] = [71, 93,54]
a[2] = [43, 91,96]
print(a)


[[84 95 89]
 [71 93 54]
 [43 91 96]]


In [24]:
total_marks1 = np.sum(a[0])
print(total_marks1)
total_marks2 = np.sum(a[1])
print(total_marks2)
total_marks3 = np.sum(a[2])
print(total_marks3)

268
218
230


In [26]:
percentage_1=(total_marks1/(3*100))*100
print(percentage_1, "%")
percentage_2=(total_marks2/(3*100))*100
print(percentage_2, "%")
percentage_3=(total_marks3/(3*100))*100
print(percentage_3, "%")

89.33333333333333 %
72.66666666666667 %
76.66666666666667 %


In [40]:
from tabulate import tabulate
table_result=[["Amadou",268, 89.33, "A"],
              ["Souleye",218, 72.67, "B+"],
              ["Penda",230, 76.67, "B+"]]
print(tabulate(table_result, headers=["student name", "total marks", "percentage", "grade"], tablefmt='orgtbl'))
              


| student name   |   total marks |   percentage | grade   |
|----------------+---------------+--------------+---------|
| Amadou         |           268 |        89.33 | A       |
| Souleye        |           218 |        72.67 | B+      |
| Penda          |           230 |        76.67 | B+      |
